### ISSUE TITLE
Delaying repeater transmission

### ISSUE THREAD

**Issue by Anjum9694** [allebb/pirrot#21]
Greetings.

Great project! I was wondering how it can be done with this.. Repeating back a transmission after a set time delay for example 5 seconds..

**Comment by allebb** [comment]
Sure - I will start work on this next month (when I have a bit more spare time).

**Comment by allebb** [comment]
Sorry for the super delay in this, I have more spare time now and plan to get this optional feature added over the next couple of weeks 👍

**Comment by allebb** [comment]
This has now been implemented, the optional transmission delay can now be added by adjusting the value of the new configuration option ``delayed_playback_interval`` in **/etc/pirrot.conf**, by default this value is set to ``0`` thus no transmission delay is applied.

This has been implemented and tested (currently in our 'dev-1.0.5' branch), and will be released in the next release of Pirrot.
