### ISSUE TITLE
Question: Possible to change VOX Receive sensitivity somehow?

### ISSUE THREAD

**Issue by ad1k4h** [allebb/pirrot#36]
I started to use this amazing app, and i would like to ask, how can i change the vox recording sensitivity without adjusting the volume? If i change the volume, the recordings becomes distorted. But i would like to decrease a little bit the record start sensitivity.

Thanks!

**Comment by motormayhem** [comment]
I would like to do the same. If I talk loudly into the mic it works. If I talk normal the Vox doesn't pick it up.

**Comment by allebb** [comment]
Have you tried adjusting the microphone input volume settings in Linux? You
should just have to increase the Microphone input volume to resolve this
issue :)

Let me know how you get on :+1

**Comment by allebb** [comment]
Ps. These commands should help you get to the sound mixer settings in Linux (if you're not familiar with it):

>Using the `alsamixer` command in the terminal you can adjust your microphone and speaker volumes if required.

>If you do adjust the volume, remember that to permanently save these settings use the `alsactl store` command to ensure they are kept after reboot.

The above was taken from my README file at: https://github.com/allebb/pirrot/blob/master/README.md

**Comment by motormayhem** [comment]
At least for me I have my audio levels set to accommodate a few other programs I play with (JS8 Call, Direwolf, etc) so I was hoping to leave the global audio levels the same and just adjust the Vox down a bit.

**Comment by allebb** [comment]
Leave it with me then... I'll have to see if there are any available arguments that I can pass to the sound recording software to vary the VOX (sound input) levels independently of the global sound mixer.

I'm busy today and tomorrow (family stuff) but remind me in a few days if you've not heard back from me... :D

**Comment by motormayhem** [comment]
Thanks! I really appreciate it. This software looks like it has a lot of potential to make a nice addition to the portable camping rig!

**Comment by allebb** [comment]
No worries @motormayhem - I'm pleased you like it and see the potential :) - Like I said, give me a shout in a few days if you've not heard back from me, which will prompt me to sort it out for you 👍

**Comment by motormayhem** [comment]
Hi Allebb,
Just circling back to this....were you ever able to implement this?

**Comment by allebb** [comment]
I know it's been a while but just wanted to let you know that I'm now working on v3.3.0 and have found a solution to enable you to independently (from the mic input) adjust the VOX levels, I will be adding a new setting into the Pirrot configuration to enable you to adjust this to your exact requirements.

Should be released shortly!

**Comment by allebb** [comment]
This is now implemented and has been released as part of Pirrot v3.3.0 as shown here: https://github.com/allebb/pirrot/releases/tag/v3.3.0

**Comment by motormayhem** [comment]
I haven't had a chance to try it yet, but thanks for the follow up!

**Comment by allebb** [comment]
No problem - You’re welcome!

Let me know how it goes (when you get a chance).

Cheers,
Bobby
